import Co from './CConstants'
import Utils from './CCUtils'
import CCPreference from './CCPreference'
import Logger from './Logger'
import { WindowBarManager } from '../common/WindowBar';
import { GlobalData } from './GlobalData'

// common 文件导出
let CM = {
  Co: Co,
  Utils: Utils,
  CCPreference: CCPreference,
  Logger: Logger,
  WindowBarManager: WindowBarManager,
  GlobalData: GlobalData,
};
export default CM;
