
/**
 * Common constants
 */
export  default class CConstants {

  // UIKet tab index
  static readonly UIKIT_TAB_INDEX = 0

  // Case tab index
  static readonly CASE_TAB_INDEX = 1

  // Common Spacing of Components
  static readonly SPACE = '12vp'

  // Table bar height
  static readonly BAR_HEIGHT = '56vp'

  // Navigation bar height
  static readonly NAV_BAR_HEIGHT = '140vp'

  // The width or height of the component is spread across the parent component.
  static readonly  FULL_PARENT = '100%'

  static readonly  HALF_PARENT = '50%'

  static readonly TRANSPARENT_COLOR: string = '#00ffffff'
  static readonly NAVIGATION_BAR_COLOR: string = '#00ff00'
  static readonly STATUS_BAR_CONTENT_COLOR: string = '#ffffff'
  static readonly NAVIGATION_BAR_CONTENT_COLOR: string = '#ffffff'

}

// 资源类型别名定义
type ResourceStr = Resource | string
